### ISSUE TITLE
warp::server] server error: executor failed to spawn task: tokio::spawn failed (is a tokio runtime running this future?)

### ISSUE THREAD

**Issue by bbigras** [seanmonstar/warp#275]
I didn't have this problem with either an old nightly or older version of the crates. not sure.

nightly-2019-09-13-i686-pc-windows-msvc

EDIT:
I also have the same result with `rustc 1.39.0-nightly (eb48d6bde 2019-09-12)` on Linux.

```toml
[dependencies]
env_logger = "0.7"
futures-preview = { version = "0.3.0-alpha.17", features = ["compat"] }
log = "0.4"
tokio = "0.2.0-alpha.5"
warp = "0.1"
```

```rust
use env_logger::Env;
use warp::Filter;

use futures::compat::Future01CompatExt;

#[tokio::main]
async fn main() -> Result<(), std::io::Error> {
    let log_env = Env::default().filter_or("RUST_LOG", "debug");
    env_logger::init_from_env(log_env);

    let routes = warp::get2().and(warp::fs::dir("app/build"));
    let f = warp::serve(routes).bind(([0, 0, 0, 0], 8080));
    if let Err(e) = f.compat().await {
        println!("error: {:?}", e);
    }
    Ok(())
}
```

```
[2019-09-24T20:26:12Z WARN  hyper::common::exec] executor error: SpawnError { is_shutdown: true }
[2019-09-24T20:26:12Z ERROR warp::server] server error: executor failed to spawn task: tokio::spawn failed (is a tokio runtime running this future?)
```
